version: 2.1

#orbs:
#  php: circleci/php@1.0.1
#  node: circleci/node@4.0.0

workflows:
  lint-and-test:
    jobs:
      - tests


jobs:
  tests:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Install PHP and Composer
          command: |
            sudo add-apt-repository ppa:ondrej/php
            sudo apt-get update
            sudo apt-get install php php-xml php-mbstring
            sudo apt-get install curl
            sudo curl -s https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
      - run:
          name: Install composer packages
          command: |
            composer install
      - restore_cache:
          name: Restore node modules cache
          key: node_modules-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
            name: Save node modules cache
            key: cache-{{ checksum "package.json" }}
            paths:
              - ~/.npm
              - ~/.cache
      - run:
          name: Start wp-cypress
          command: npx wp-cypress start
      - run:
          name: Run Cypress tests
          command: ./node_modules/cypress/bin/cypress run
      - store_artifacts:
          path: tests/functional/cypress/screenshots
